# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created: Fri Aug 14 14:06:40 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from pyqtgraph import PlotWidget

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1670, 1030)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        
     
        #Plot widgets
        self.graph_enrichrate = PlotWidget(self.centralwidget, name='rate')
        self.graph_enrichrate.setGeometry(QtCore.QRect(1000, 340, 661, 631))
        self.graph_enrichrate.setObjectName(_fromUtf8("graph_enrichrate"))

        self.graph_rawdata = PlotWidget(self.centralwidget, name='raw')
        self.graph_rawdata.setGeometry(QtCore.QRect(10, 10, 981, 961))
        self.graph_rawdata.setObjectName(_fromUtf8("graph_rawdata"))

        self.graph_enrichrate.setXLink('raw')

        self.btn_lighton = QtGui.QPushButton(self.centralwidget)
        self.btn_lighton.setGeometry(QtCore.QRect(1043, 177, 85, 28))
        self.btn_lighton.setObjectName(_fromUtf8("btn_lighton"))
        self.btn_lightoff = QtGui.QPushButton(self.centralwidget)
        self.btn_lightoff.setGeometry(QtCore.QRect(1043, 212, 85, 28))
        self.btn_lightoff.setObjectName(_fromUtf8("btn_lightoff"))
        self.btn_bic = QtGui.QPushButton(self.centralwidget)
        self.btn_bic.setGeometry(QtCore.QRect(1043, 37, 85, 28))
        self.btn_bic.setObjectName(_fromUtf8("btn_bic"))
        self.btn_cells = QtGui.QPushButton(self.centralwidget)
        self.btn_cells.setGeometry(QtCore.QRect(1043, 72, 85, 28))
        self.btn_cells.setObjectName(_fromUtf8("btn_cells"))
        self.btn_az = QtGui.QPushButton(self.centralwidget)
        self.btn_az.setGeometry(QtCore.QRect(1043, 107, 85, 28))
        self.btn_az.setObjectName(_fromUtf8("btn_az"))
        self.btn_ez = QtGui.QPushButton(self.centralwidget)
        self.btn_ez.setGeometry(QtCore.QRect(1043, 142, 85, 28))
        self.btn_ez.setObjectName(_fromUtf8("btn_ez"))
        self.cells_vol = QtGui.QLineEdit(self.centralwidget)
        self.cells_vol.setGeometry(QtCore.QRect(1135, 75, 58, 22))
        self.cells_vol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cells_vol.setObjectName(_fromUtf8("cells_vol"))
        self.ez_vol = QtGui.QLineEdit(self.centralwidget)
        self.ez_vol.setGeometry(QtCore.QRect(1135, 145, 58, 22))
        self.ez_vol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ez_vol.setObjectName(_fromUtf8("ez_vol"))
        self.bic_vol = QtGui.QLineEdit(self.centralwidget)
        self.bic_vol.setGeometry(QtCore.QRect(1135, 40, 58, 22))
        self.bic_vol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bic_vol.setObjectName(_fromUtf8("bic_vol"))
        self.az_vol = QtGui.QLineEdit(self.centralwidget)
        self.az_vol.setGeometry(QtCore.QRect(1135, 110, 58, 22))
        self.az_vol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.az_vol.setObjectName(_fromUtf8("az_vol"))
        self.bic_cc = QtGui.QLineEdit(self.centralwidget)
        self.bic_cc.setGeometry(QtCore.QRect(1221, 40, 58, 22))
        self.bic_cc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bic_cc.setObjectName(_fromUtf8("bic_cc"))
        self.lab_bicvolunit = QtGui.QLabel(self.centralwidget)
        self.lab_bicvolunit.setGeometry(QtCore.QRect(1200, 40, 16, 16))
        self.lab_bicvolunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_bicvolunit.setObjectName(_fromUtf8("lab_bicvolunit"))
        self.lab_bicccunit = QtGui.QLabel(self.centralwidget)
        self.lab_bicccunit.setGeometry(QtCore.QRect(1286, 42, 16, 16))
        self.lab_bicccunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_bicccunit.setObjectName(_fromUtf8("lab_bicccunit"))
        self.lab_cellsvolunit = QtGui.QLabel(self.centralwidget)
        self.lab_cellsvolunit.setGeometry(QtCore.QRect(1200, 75, 16, 16))
        self.lab_cellsvolunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_cellsvolunit.setObjectName(_fromUtf8("lab_cellsvolunit"))
        self.lab_cellsccunit = QtGui.QLabel(self.centralwidget)
        self.lab_cellsccunit.setGeometry(QtCore.QRect(1286, 75, 36, 16))
        self.lab_cellsccunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_cellsccunit.setObjectName(_fromUtf8("lab_cellsccunit"))
        self.cells_cc = QtGui.QLineEdit(self.centralwidget)
        self.cells_cc.setGeometry(QtCore.QRect(1221, 75, 58, 22))
        self.cells_cc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cells_cc.setObjectName(_fromUtf8("cells_cc"))
        self.lab_azvolunit = QtGui.QLabel(self.centralwidget)
        self.lab_azvolunit.setGeometry(QtCore.QRect(1200, 110, 16, 16))
        self.lab_azvolunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_azvolunit.setObjectName(_fromUtf8("lab_azvolunit"))
        self.lab_ezvolunit = QtGui.QLabel(self.centralwidget)
        self.lab_ezvolunit.setGeometry(QtCore.QRect(1200, 145, 16, 16))
        self.lab_ezvolunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_ezvolunit.setObjectName(_fromUtf8("lab_ezvolunit"))
        self.az_cc = QtGui.QLineEdit(self.centralwidget)
        self.az_cc.setGeometry(QtCore.QRect(1221, 110, 58, 22))
        self.az_cc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.az_cc.setObjectName(_fromUtf8("az_cc"))
        self.ez_cc = QtGui.QLineEdit(self.centralwidget)
        self.ez_cc.setGeometry(QtCore.QRect(1221, 145, 58, 22))
        self.ez_cc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ez_cc.setObjectName(_fromUtf8("ez_cc"))
        self.lab_azccunit = QtGui.QLabel(self.centralwidget)
        self.lab_azccunit.setGeometry(QtCore.QRect(1286, 110, 21, 16))
        self.lab_azccunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_azccunit.setObjectName(_fromUtf8("lab_azccunit"))
        self.lab_ezccunit = QtGui.QLabel(self.centralwidget)
        self.lab_ezccunit.setGeometry(QtCore.QRect(1286, 145, 21, 16))
        self.lab_ezccunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_ezccunit.setObjectName(_fromUtf8("lab_ezccunit"))
        self.lab_lightintunit = QtGui.QLabel(self.centralwidget)
        self.lab_lightintunit.setGeometry(QtCore.QRect(1200, 180, 16, 16))
        self.lab_lightintunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_lightintunit.setObjectName(_fromUtf8("lab_lightintunit"))
        self.light_int = QtGui.QLineEdit(self.centralwidget)
        self.light_int.setGeometry(QtCore.QRect(1135, 180, 58, 22))
        self.light_int.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.light_int.setObjectName(_fromUtf8("light_int"))
        self.btn_custom = QtGui.QPushButton(self.centralwidget)
        self.btn_custom.setGeometry(QtCore.QRect(1043, 247, 85, 28))
        self.btn_custom.setObjectName(_fromUtf8("btn_custom"))
        self.custom_text = QtGui.QLineEdit(self.centralwidget)
        self.custom_text.setGeometry(QtCore.QRect(1135, 250, 181, 22))
        self.custom_text.setText(_fromUtf8(""))
        self.custom_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.custom_text.setObjectName(_fromUtf8("custom_text"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1410, 10, 246, 321))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chk_logE = QtGui.QCheckBox(self.layoutWidget)
        self.chk_logE.setChecked(True)
        self.chk_logE.setObjectName(_fromUtf8("chk_logE"))
        self.gridLayout.addWidget(self.chk_logE, 0, 0, 1, 1)
        self.lab_logE = QtGui.QLabel(self.layoutWidget)
        self.lab_logE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_logE.setObjectName(_fromUtf8("lab_logE"))
        self.gridLayout.addWidget(self.lab_logE, 0, 2, 1, 1)
        self.chk_ER47 = QtGui.QCheckBox(self.layoutWidget)
        self.chk_ER47.setChecked(True)
        self.chk_ER47.setObjectName(_fromUtf8("chk_ER47"))
        self.gridLayout.addWidget(self.chk_ER47, 1, 0, 1, 2)
        self.lab_ER47 = QtGui.QLabel(self.layoutWidget)
        self.lab_ER47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_ER47.setObjectName(_fromUtf8("lab_ER47"))
        self.gridLayout.addWidget(self.lab_ER47, 1, 2, 1, 1)
        self.lab_ER47unit = QtGui.QLabel(self.layoutWidget)
        self.lab_ER47unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_ER47unit.setObjectName(_fromUtf8("lab_ER47unit"))
        self.gridLayout.addWidget(self.lab_ER47unit, 1, 3, 1, 1)
        self.chk_ER49 = QtGui.QCheckBox(self.layoutWidget)
        self.chk_ER49.setChecked(True)
        self.chk_ER49.setObjectName(_fromUtf8("chk_ER49"))
        self.gridLayout.addWidget(self.chk_ER49, 2, 0, 1, 2)
        self.lab_ER49 = QtGui.QLabel(self.layoutWidget)
        self.lab_ER49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_ER49.setObjectName(_fromUtf8("lab_ER49"))
        self.gridLayout.addWidget(self.lab_ER49, 2, 2, 1, 1)
        self.lab_ER49unit = QtGui.QLabel(self.layoutWidget)
        self.lab_ER49unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_ER49unit.setObjectName(_fromUtf8("lab_ER49unit"))
        self.gridLayout.addWidget(self.lab_ER49unit, 2, 3, 1, 1)
        self.chk_O2evol = QtGui.QCheckBox(self.layoutWidget)
        self.chk_O2evol.setChecked(True)
        self.chk_O2evol.setObjectName(_fromUtf8("chk_O2evol"))
        self.gridLayout.addWidget(self.chk_O2evol, 3, 0, 1, 2)
        self.lab_O2evol = QtGui.QLabel(self.layoutWidget)
        self.lab_O2evol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_O2evol.setObjectName(_fromUtf8("lab_O2evol"))
        self.gridLayout.addWidget(self.lab_O2evol, 3, 2, 1, 1)
        self.lab_O2evolunit = QtGui.QLabel(self.layoutWidget)
        self.lab_O2evolunit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_O2evolunit.setObjectName(_fromUtf8("lab_O2evolunit"))
        self.gridLayout.addWidget(self.lab_O2evolunit, 3, 3, 1, 1)
        self.chk_M32 = QtGui.QCheckBox(self.layoutWidget)
        self.chk_M32.setChecked(True)
        self.chk_M32.setObjectName(_fromUtf8("chk_M32"))
        self.gridLayout.addWidget(self.chk_M32, 4, 0, 1, 1)
        self.lab_32 = QtGui.QLabel(self.layoutWidget)
        self.lab_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_32.setObjectName(_fromUtf8("lab_32"))
        self.gridLayout.addWidget(self.lab_32, 4, 1, 1, 1)
        self.chk_M40 = QtGui.QCheckBox(self.layoutWidget)
        self.chk_M40.setChecked(True)
        self.chk_M40.setObjectName(_fromUtf8("chk_M40"))
        self.gridLayout.addWidget(self.chk_M40, 5, 0, 1, 1)
        self.lab_40 = QtGui.QLabel(self.layoutWidget)
        self.lab_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_40.setObjectName(_fromUtf8("lab_40"))
        self.gridLayout.addWidget(self.lab_40, 5, 1, 1, 1)
        self.chk_M44 = QtGui.QCheckBox(self.layoutWidget)
        self.chk_M44.setChecked(True)
        self.chk_M44.setObjectName(_fromUtf8("chk_M44"))
        self.gridLayout.addWidget(self.chk_M44, 6, 0, 1, 1)
        self.lab_44 = QtGui.QLabel(self.layoutWidget)
        self.lab_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_44.setObjectName(_fromUtf8("lab_44"))
        self.gridLayout.addWidget(self.lab_44, 6, 1, 1, 1)
        self.chk_M45 = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.chk_M45.setFont(font)
        self.chk_M45.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chk_M45.setChecked(True)
        self.chk_M45.setObjectName(_fromUtf8("chk_M45"))
        self.gridLayout.addWidget(self.chk_M45, 7, 0, 1, 1)
        self.lab_45 = QtGui.QLabel(self.layoutWidget)
        self.lab_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_45.setObjectName(_fromUtf8("lab_45"))
        self.gridLayout.addWidget(self.lab_45, 7, 1, 1, 1)
        self.chk_M46 = QtGui.QCheckBox(self.layoutWidget)
        self.chk_M46.setChecked(True)
        self.chk_M46.setObjectName(_fromUtf8("chk_M46"))
        self.gridLayout.addWidget(self.chk_M46, 8, 0, 1, 1)
        self.lab_46 = QtGui.QLabel(self.layoutWidget)
        self.lab_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_46.setObjectName(_fromUtf8("lab_46"))
        self.gridLayout.addWidget(self.lab_46, 8, 1, 1, 1)
        self.chk_M47 = QtGui.QCheckBox(self.layoutWidget)
        self.chk_M47.setChecked(True)
        self.chk_M47.setObjectName(_fromUtf8("chk_M47"))
        self.gridLayout.addWidget(self.chk_M47, 9, 0, 1, 1)
        self.lab_47 = QtGui.QLabel(self.layoutWidget)
        self.lab_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_47.setObjectName(_fromUtf8("lab_47"))
        self.gridLayout.addWidget(self.lab_47, 9, 1, 1, 1)
        self.chk_M49 = QtGui.QCheckBox(self.layoutWidget)
        self.chk_M49.setChecked(True)
        self.chk_M49.setObjectName(_fromUtf8("chk_M49"))
        self.gridLayout.addWidget(self.chk_M49, 10, 0, 1, 1)
        self.lab_49 = QtGui.QLabel(self.layoutWidget)
        self.lab_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_49.setObjectName(_fromUtf8("lab_49"))
        self.gridLayout.addWidget(self.lab_49, 10, 1, 1, 1)
        self.lab_smoothing = QtGui.QLabel(self.layoutWidget)
        self.lab_smoothing.setObjectName(_fromUtf8("lab_smoothing"))
        self.gridLayout.addWidget(self.lab_smoothing, 11, 0, 1, 1)
        self.smoothing_value = QtGui.QSpinBox(self.layoutWidget)
        self.smoothing_value.setProperty("value", 60)
        self.smoothing_value.setProperty("maximum",999)
        self.smoothing_value.setProperty("minimum",1)
        self.smoothing_value.setObjectName(_fromUtf8("smoothing_value"))
        self.gridLayout.addWidget(self.smoothing_value, 11, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1670, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuStart = QtGui.QMenu(self.menubar)
        self.menuStart.setObjectName(_fromUtf8("menuStart"))
        self.menuQuit = QtGui.QMenu(self.menubar)
        self.menuQuit.setObjectName(_fromUtf8("menuQuit"))
        self.menuCalibrations = QtGui.QMenu(self.menubar)
        self.menuCalibrations.setObjectName(_fromUtf8("menuCalibrations"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionTestmode = QtGui.QAction(MainWindow)
        self.actionTestmode.setObjectName(_fromUtf8("actionTestmode"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionSet_datafile = QtGui.QAction(MainWindow)
        self.actionSet_datafile.setObjectName(_fromUtf8("actionSet_datafile"))
        self.actionSet_duration = QtGui.QAction(MainWindow)
        self.actionSet_duration.setObjectName(_fromUtf8("actionSet_duration"))
        self.actionStop_2 = QtGui.QAction(MainWindow)
        self.actionStop_2.setObjectName(_fromUtf8("actionStop_2"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAdd_new_Membrane = QtGui.QAction(MainWindow)
        self.actionAdd_new_Membrane.setObjectName(_fromUtf8("actionAdd_new_Membrane"))
        self.actionAdd_CO2_Calibration = QtGui.QAction(MainWindow)
        self.actionAdd_CO2_Calibration.setObjectName(_fromUtf8("actionAdd_CO2_Calibration"))
        self.actionAdd_O2_Calibration = QtGui.QAction(MainWindow)
        self.actionAdd_O2_Calibration.setObjectName(_fromUtf8("actionAdd_O2_Calibration"))
        self.actionAdd_Electrical_Zeros = QtGui.QAction(MainWindow)
        self.actionAdd_Electrical_Zeros.setObjectName(_fromUtf8("actionAdd_Electrical_Zeros"))
        self.actionAdd_Consumptions = QtGui.QAction(MainWindow)
        self.actionAdd_Consumptions.setObjectName(_fromUtf8("actionAdd_Consumptions"))
        self.menuStart.addAction(self.actionStart)
        self.menuStart.addSeparator()
        self.menuStart.addAction(self.actionStop_2)
        self.menuStart.addSeparator()
        self.menuStart.addAction(self.actionTestmode)
        self.menuQuit.addAction(self.actionQuit)
        self.menuCalibrations.addAction(self.actionAdd_new_Membrane)
        self.menuCalibrations.addSeparator()
        self.menuCalibrations.addAction(self.actionAdd_CO2_Calibration)
        self.menuCalibrations.addAction(self.actionAdd_O2_Calibration)
        self.menuCalibrations.addSeparator()
        self.menuCalibrations.addAction(self.actionAdd_Electrical_Zeros)
        self.menuCalibrations.addSeparator()
        self.menuCalibrations.addAction(self.actionAdd_Consumptions)
        self.menubar.addAction(self.menuStart.menuAction())
        self.menubar.addAction(self.menuCalibrations.menuAction())
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "dAcq_v3", None))
        self.btn_lighton.setText(_translate("MainWindow", "Light ON [5]", None))
        self.btn_lightoff.setText(_translate("MainWindow", "Light OFF [6]", None))
        self.btn_bic.setText(_translate("MainWindow", "+ Bic [1]", None))
        self.btn_cells.setText(_translate("MainWindow", "+ Cells [2]", None))
        self.btn_az.setText(_translate("MainWindow", "+ AZ [3]", None))
        self.btn_ez.setText(_translate("MainWindow", "+ EZ [4]", None))
        self.cells_vol.setText(_translate("MainWindow", "20", None))
        self.ez_vol.setText(_translate("MainWindow", "0", None))
        self.bic_vol.setText(_translate("MainWindow", "1", None))
        self.az_vol.setText(_translate("MainWindow", "0", None))
        self.bic_cc.setText(_translate("MainWindow", "0.5", None))
        self.lab_bicvolunit.setText(_translate("MainWindow", "µL", None))
        self.lab_bicccunit.setText(_translate("MainWindow", "M", None))
        self.lab_cellsvolunit.setText(_translate("MainWindow", "µL", None))
        self.lab_cellsccunit.setText(_translate("MainWindow", "µg/mL", None))
        self.cells_cc.setText(_translate("MainWindow", "20", None))
        self.lab_azvolunit.setText(_translate("MainWindow", "µL", None))
        self.lab_ezvolunit.setText(_translate("MainWindow", "µL", None))
        self.az_cc.setText(_translate("MainWindow", "5", None))
        self.ez_cc.setText(_translate("MainWindow", "5", None))
        self.lab_azccunit.setText(_translate("MainWindow", "mM", None))
        self.lab_ezccunit.setText(_translate("MainWindow", "mM", None))
        self.lab_lightintunit.setText(_translate("MainWindow", "µE", None))
        self.light_int.setText(_translate("MainWindow", "0", None))
        self.btn_custom.setText(_translate("MainWindow", "Custom [7]", None))
        self.chk_logE.setText(_translate("MainWindow", "LogEnrich", None))
        self.lab_logE.setText(_translate("MainWindow", "0", None))
        self.chk_ER47.setText(_translate("MainWindow", "EnrichRate(47)", None))
        self.lab_ER47.setText(_translate("MainWindow", "0", None))
        self.lab_ER47unit.setText(_translate("MainWindow", "min-1", None))
        self.chk_ER49.setText(_translate("MainWindow", "EnrichRate(49)", None))
        self.lab_ER49.setText(_translate("MainWindow", "0", None))
        self.lab_ER49unit.setText(_translate("MainWindow", "min-1", None))
        self.chk_O2evol.setText(_translate("MainWindow", "O2 Evolution", None))
        self.lab_O2evol.setText(_translate("MainWindow", "0", None))
        self.lab_O2evolunit.setText(_translate("MainWindow", "mmol.l-1.min-1", None))
        self.chk_M32.setText(_translate("MainWindow", "Mass32: ", None))
        self.lab_32.setText(_translate("MainWindow", "0", None))
        self.chk_M40.setText(_translate("MainWindow", "Mass40: ", None))
        self.lab_40.setText(_translate("MainWindow", "0", None))
        self.chk_M44.setText(_translate("MainWindow", "Mass44: ", None))
        self.lab_44.setText(_translate("MainWindow", "0", None))
        self.chk_M45.setText(_translate("MainWindow", "Mass45: ", None))
        self.lab_45.setText(_translate("MainWindow", "0", None))
        self.chk_M46.setText(_translate("MainWindow", "Mass46:", None))
        self.lab_46.setText(_translate("MainWindow", "0", None))
        self.chk_M47.setText(_translate("MainWindow", "Mass47: ", None))
        self.lab_47.setText(_translate("MainWindow", "0", None))
        self.chk_M49.setText(_translate("MainWindow", "Mass49: ", None))
        self.lab_49.setText(_translate("MainWindow", "0", None))
        self.lab_smoothing.setText(_translate("MainWindow", "Smoothing:", None))
        self.menuStart.setTitle(_translate("MainWindow", "Acquire", None))
        self.menuQuit.setTitle(_translate("MainWindow", "Quit", None))
        self.menuCalibrations.setTitle(_translate("MainWindow", "Calibrations", None))
        self.actionStart.setText(_translate("MainWindow", "Start", None))
        self.actionStart.setShortcut(_translate("MainWindow", "Ctrl+F1", None))
        self.actionTestmode.setText(_translate("MainWindow", "Start Testmode", None))
        self.actionTestmode.setShortcut(_translate("MainWindow", "Ctrl+F3", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionStop.setShortcut(_translate("MainWindow", "F1", None))
        self.actionSet_datafile.setText(_translate("MainWindow", "Set datafile", None))
        self.actionSet_duration.setText(_translate("MainWindow", "Set duration", None))
        self.actionStop_2.setText(_translate("MainWindow", "Stop", None))
        self.actionStop_2.setShortcut(_translate("MainWindow", "Ctrl+F2", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAdd_new_Membrane.setText(_translate("MainWindow", "Add new Membrane", None))
        self.actionAdd_CO2_Calibration.setText(_translate("MainWindow", "Add CO2 Calibration", None))
        self.actionAdd_O2_Calibration.setText(_translate("MainWindow", "Add O2 Calibration", None))
        self.actionAdd_Electrical_Zeros.setText(_translate("MainWindow", "Add Electrical Zeros", None))
        self.actionAdd_Consumptions.setText(_translate("MainWindow", "Add Consumptions", None))

        self.chk_M32.setStyleSheet("color:rgb(250,0,0)")
        self.chk_M40.setStyleSheet("color:rgb(200,150,0)")
        self.chk_M44.setStyleSheet("color:rgb(0,250,0)")
        self.chk_M45.setStyleSheet("color:rgb(50,200,250)")
        self.chk_M46.setStyleSheet("color:rgb(250,150,250)")
        self.chk_M47.setStyleSheet("color:rgb(0,100,250)")
        self.chk_M49.setStyleSheet("color:rgb(100,0,250)")
        #self.chk_totCO2.setStyleSheet("color:rgb(100,100,100)")
        self.chk_logE.setStyleSheet("color:rgb(0,0,0)")
        self.chk_ER47.setStyleSheet("color:rgb(0,100,250)")
        self.chk_ER49.setStyleSheet("color:rgb(100,0,250)")
        self.chk_O2evol.setStyleSheet("color:rgb(250,0,0)")


